#!/bin/bash

score=0
count=1
quit=0

echo "Welcome to the game!"
echo "At any question prompt, type 'q + return' to quit the game."
echo ""
echo "Enter a mode to play: ((a)ddition, (s)ubtraction, (m)ultiplication, (d)ivision)"
read -p "" mode

echo ""

while [[ $quit -eq 0 ]]; do
	num1=$((RANDOM % 74 + 1))
	num2=$((RANDOM % 74 + 1))

	case "$mode" in
		a)
			answer=$((num1+num2))
			question="$num1 + $num2"
			;;
		s)
			answer=$((num1-num2))
			question="$num1 - $num2"
			;;
		m)
			answer=$((num1*num2))
			question="$num1 * $num2"
			;;
		d)
			num2=$((RANDOM % 74 + 1))
			answer=$((RANDOM % 74 + 1))
			num1=$((num2 * answer))
			question="$num1 / $num2"
			;;
		*)
			echo "Invalid mode. Quitting game."
			exit 1
			;;
	esac

	echo "$count. What is $question?"
	read -p "" input

	# Quit Check
	if [[ "$input" == "q" ]]; then
		echo "You answered $score out of $((count-1)) questions correctly."
		quit=1
	else
		# Answer Check
		if [[ "$input" -eq "$answer" ]]; then
			echo "Your answer was correct."
			((score++))
		else
			echo "Your answer was incorrect. The correct answer is $answer."
		fi
		((count++))
		echo ""

		sleep 0.5
	fi
done